import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent


def test_required_directories_exist():
    for path in ["core", "input", "output", "tools", "data/chroma_db", "data/logs", "tests"]:
        assert (ROOT / path).exists()


def test_env_template_contains_required_keys():
    text = (ROOT / ".env").read_text(encoding="utf-8")
    for key in [
        "ANTHROPIC_API_KEY",
        "ELEVENLABS_API_KEY",
        "ELEVENLABS_VOICE_ID",
        "ALPHA_VANTAGE_KEY",
        "GMAIL_ADDRESS",
        "GMAIL_APP_PASSWORD",
        "GROQ_API_KEY",
        "GEMINI_API_KEY",
        "OPENROUTER_API_KEY",
        "NVIDIA_API_KEY",
        "MESHY_API_KEY",
        "TRIPO_API_KEY",
        "BRAVE_SEARCH_API_KEY",
        "GOOGLE_SEARCH_API_KEY",
        "GOOGLE_SEARCH_CX",
        "TAVILY_API_KEY",
        "SERPAPI_API_KEY",
        "JARVIS_API_USERNAME",
        "JARVIS_API_PASSWORD",
        "JARVIS_API_SECRET",
    ]:
        assert f"{key}=" in text


def test_config_json_contains_required_keys():
    config = json.loads((ROOT / "config.json").read_text(encoding="utf-8"))
    for key in [
        "jarvis_name",
        "audio_input_device",
        "voice_rate",
        "voice_volume",
        "pyttsx3_voice_id",
        "voice_backend",
        "fast_voice_use_local_tts",
        "fast_voice_edge_rate",
        "fast_voice_edge_pitch",
        "fast_voice_edge_voice",
        "edge_persistent_cache_enabled",
        "edge_persistent_cache_max_files",
        "elevenlabs_voice_id",
        "allowed_apps",
        "blocked_paths",
        "daily_email_limit",
        "supported_symbols",
        "memory_max_turns",
        "memory_backend",
        "memory_activation_decay_rate",
        "memory_activation_prune_threshold",
        "memory_consolidation_enabled",
        "context_budget_max_tokens",
        "context_include_conversation_section",
        "competence_map_template",
        "competence_research_threshold",
        "competence_learning_rate",
        "procedural_skill_min_examples",
        "procedural_skill_prompt_limit",
        "v2_agent_autonomous_research_enabled",
        "v2_agent_delegation_enabled",
        "v2_dynamic_decomposition_enabled",
        "v2_mentoring_enabled",
        "v2_max_subtasks_per_task",
        "research_max_sources",
        "research_fetch_pages",
        "search_broker_enabled",
        "search_broker_provider_chain",
        "search_broker_mode",
        "search_broker_min_results_before_fallback",
        "search_broker_max_results",
        "search_broker_tool_results",
        "search_broker_cache_enabled",
        "search_broker_cache_ttl_seconds",
        "search_broker_request_timeout_seconds",
        "search_broker_country",
        "search_broker_language",
        "search_broker_safe_search",
        "search_broker_rerank_enabled",
        "search_broker_allow_legacy_fallback",
        "search_broker_domain_boosts",
        "search_broker_brave_api_key_env",
        "search_broker_brave_base_url",
        "search_broker_google_api_key_env",
        "search_broker_google_cx_env",
        "search_broker_google_base_url",
        "search_broker_tavily_api_key_env",
        "search_broker_tavily_base_url",
        "search_broker_tavily_search_depth",
        "search_broker_tavily_topic",
        "search_broker_tavily_country",
        "search_broker_serpapi_api_key_env",
        "search_broker_serpapi_base_url",
        "v2_background_agents_enabled",
        "v2_background_worker_count",
        "v2_api_agent_mode_enabled",
        "v2_api_background_worker_count",
        "v2_api_agent_force_online_first",
        "v2_api_agent_online_providers",
        "v2_start_background_workers_in_fast_voice",
        "v2_cpu_guard_enabled",
        "v2_max_cpu_percent",
        "v2_worker_cpu_guard_sleep_seconds",
        "v2_self_learning_enabled",
        "v2_self_learning_priority",
        "v2_self_learning_delay_minutes",
        "v2_self_learning_repeat_hours",
        "v2_agent_use_llm",
        "v2_agent_questions_enabled",
        "v2_agent_provider_routes",
        "agent_office_task_limit",
        "agent_blackboard_prompt_limit",
        "agent_thought_bus_enabled",
        "agent_thought_bus_prompt_limit",
        "agent_thought_bus_default_ttl_hours",
        "agent_memory_prompt_limit",
        "google_oauth_enabled",
        "google_oauth_client_id_env",
        "google_oauth_client_secret_env",
        "google_oauth_redirect_uri",
        "google_oauth_timezone",
        "google_oauth_scopes",
        "self_update_enabled",
        "self_update_task_priority",
        "self_update_run_tests",
        "self_update_test_command",
        "self_update_test_timeout_seconds",
        "self_update_rollback_on_test_failure",
        "self_update_max_file_bytes",
        "self_update_max_change_bytes",
        "self_update_max_repo_summary_files",
        "self_update_max_file_candidates",
        "safe_command_allowlist",
        "performance_budget_api_import_seconds",
        "performance_budget_orchestrator_import_seconds",
        "self_model_enabled",
        "self_model_deep_activity_enabled",
        "friday_identity_file",
        "autobiographical_memory_enabled",
        "evidence_gate_enabled",
        "cognitive_cycle_enabled",
        "cognitive_cycle_light_mode_in_fast_voice",
        "cognitive_cycle_interval_seconds",
        "cognitive_context_in_llm_enabled",
        "world_model_enabled",
        "world_model_snapshot_interval_seconds",
        "world_model_max_snapshots",
        "world_model_use_vision_llm",
        "self_reflection_enabled",
        "self_reflection_interval_minutes",
        "self_reflection_window_minutes",
        "self_reflection_failure_trigger_enabled",
        "self_reflection_use_llm",
        "self_reflection_slow_latency_ms",
        "long_term_learning_enabled",
        "long_term_learning_review_interval_hours",
        "long_term_learning_min_evidence",
        "long_term_learning_self_update_enabled",
        "long_term_learning_self_update_min_evidence",
        "long_term_learning_self_update_min_confidence",
        "goal_regulation_enabled",
        "goal_regulation_default_state",
        "adaptive_attention_enabled",
        "adaptive_attention_update_interval_minutes",
        "adaptive_attention_min_events",
        "adaptive_attention_runtime_hints_only",
        "voice_reliability_enabled",
        "voice_reliability_record_samples",
        "desktop_task_expectations_enabled",
        "desktop_task_expectation_ttl_seconds",
        "desktop_task_world_model_enabled",
        "desktop_task_world_snapshots_enabled",
        "desktop_task_pc_awareness_context_enabled",
        "pc_awareness_enabled",
        "pc_awareness_cache_seconds",
        "pc_awareness_max_running_apps",
        "pc_awareness_max_installed_apps",
        "pc_awareness_max_shortcuts",
        "phone_bridge_enabled",
        "phone_bridge_default_name",
        "phone_bridge_adb_path",
        "phone_bridge_adb_serial",
        "phone_bridge_adb_timeout_seconds",
        "phone_bridge_ntfy_base_url",
        "phone_bridge_ntfy_topic",
        "phone_bridge_ntfy_token",
        "phone_bridge_ntfy_timeout_seconds",
        "phone_bridge_user_phone_number",
        "phone_bridge_allow_direct_call",
        "phone_bridge_photo_dir",
        "phone_bridge_allowed_paths",
        "home_smart_devices",
        "home_device_control_timeout_seconds",
        "home_assistant_url",
        "home_assistant_token",
        "home_assistant_timeout_seconds",
        "home_assistant_focus_entity_id",
        "workspace_project_map_max_files",
        "workspace_brain_max_repos",
        "workspace_brain_max_files",
        "workspace_brain_file_role_limit",
        "workspace_test_watch_command",
        "workspace_test_watch_timeout_seconds",
        "security_npm_audit_timeout_seconds",
        "security_pip_audit_timeout_seconds",
        "backup_allow_env_snapshot",
        "skill_marketplace_enabled",
        "personal_finance_enabled",
        "agency_mode_enabled",
        "agency_workspace_dir",
        "agency_default_currency",
        "agency_service_keywords",
        "agency_outreach_daily_limit",
        "agency_project_run_tests",
        "agency_deploy_enabled",
        "agency_default_deploy_command",
        "agency_deploy_target_url",
        "agency_deploy_timeout_seconds",
        "agency_payment_approval_required",
        "agency_api_monthly_budget",
        "agency_public_contact_email",
        "friday_gateway_enabled",
        "friday_gateway_enabled_connectors",
        "gateway_auto_task_events",
        "gateway_max_event_content_chars",
        "control_room_stream_interval_seconds",
        "connector_runtime_enabled",
        "connector_runtime_default_approval_required",
        "connector_request_timeout_seconds",
        "connector_default_daily_limit",
        "connector_max_retry_attempts",
        "connector_whatsapp_graph_version",
        "competitive_benchmark_enabled",
        "company_runtime_enabled",
        "production_coding_autonomy_enabled",
        "memory_governance_enabled",
        "memory_governance_low_confidence_threshold",
        "private_embedding_memory_enabled",
        "private_embedding_use_sentence_transformers",
        "private_embedding_chunk_chars",
        "private_embedding_max_file_bytes",
        "android_companion_enabled",
        "project_watchdog_enabled",
        "project_watchdog_interval_seconds",
        "project_watchdog_run_tests",
        "sandbox_simulation_enabled",
        "privacy_vault_enabled",
        "privacy_vault_store_plaintext",
        "model_router_brain_enabled",
        "model_router_routes",
        "self_debugger_enabled",
        "self_debugger_self_update_enabled",
        "emotion_tone_enabled",
        "emotion_tone_adjust_replies",
        "emotion_tone_adjust_min_confidence",
        "emotion_tone_adjust_min_intensity",
        "emotion_tone_context_min_confidence",
        "emotion_tone_recent_window",
        "emotion_tone_rushed_prefix_min_chars",
        "personal_crm_enabled",
        "learning_coach_enabled",
        "research_briefings_enabled",
        "research_briefing_max_sources",
        "research_briefing_task_priority",
        "contextual_workspace_enabled",
        "offline_survival_enabled",
        "offline_survival_check_hosts",
        "offline_survival_check_timeout_seconds",
        "personal_data_timeline_enabled",
        "skill_training_studio_enabled",
        "executive_capabilities_enabled",
        "memory_review_enabled",
        "task_autopilot_enabled",
        "voice_personality_profiles_enabled",
        "voice_personality_default_profile",
        "life_dashboard_enabled",
        "skill_recorder_enabled",
        "documentation_brain_enabled",
        "personal_search_enabled",
        "trust_meter_enabled",
        "learning_twin_enabled",
        "relationship_assistant_enabled",
        "deployment_commander_enabled",
        "privacy_firewall_enabled",
        "mission_control_enabled",
        "mission_default_authority_mode",
        "mission_default_deploy_policy",
        "mission_desktop_lock_enabled",
        "autonomy_control_enabled",
        "autonomy_mode",
        "autonomy_trusted_roots",
        "autonomy_preapprove_local_project_work",
        "autonomy_preapprove_git_writes",
        "autonomy_preapprove_remote_writes",
        "autonomy_preapprove_deployments",
        "autonomy_preapprove_self_updates",
        "autonomy_preapprove_design_preview",
        "autonomy_supervisor_enabled",
        "autonomy_supervisor_in_fast_voice",
        "autonomy_auto_start_api_services",
        "autonomy_start_background_workers",
        "autonomy_worker_count",
        "autonomy_supervisor_interval_seconds",
        "autonomy_supervisor_tick_max_steps",
        "autonomy_supervisor_start_runs",
        "autonomy_supervisor_new_run_interval_seconds",
        "autonomy_hard_stop_keys",
        "autonomous_qa_lab_enabled",
        "qa_lab_run_tests_default",
        "qa_lab_test_timeout_seconds",
        "app_state_memory_enabled",
        "browser_extension_bridge_enabled",
        "browser_extension_redaction_enabled",
        "release_manager_enabled",
        "error_radar_enabled",
        "semantic_search_enabled",
        "semantic_search_max_file_bytes",
        "semantic_search_chunk_chars",
        "operating_rhythm_enabled",
        "world_model_pc_awareness_enabled",
        "log_level",
        "llm_provider",
        "ollama_base_url",
        "ollama_model",
        "voice_ollama_timeout",
        "ollama_keep_alive",
        "ollama_num_predict",
        "gemini_model",
        "openrouter_model",
        "nvidia_model",
        "nvidia_base_url",
        "nvidia_api_key_env",
        "llm_provider_limits_enabled",
        "llm_provider_max_concurrency",
        "llm_provider_min_interval_seconds",
        "llm_provider_backoff_seconds",
        "llm_provider_backoff_max_seconds",
        "llm_provider_max_backoff_wait_seconds",
        "llm_provider_queue_timeout_seconds",
        "api_host",
        "api_port",
        "api_username",
        "api_password_env",
        "api_jwt_secret_env",
        "api_jwt_exp_hours",
        "api_refresh_exp_hours",
        "api_response_target_ms",
        "cloud_sync_enabled",
        "cloud_sync_interval_minutes",
        "cloud_sync_database_url_env",
        "ui_desktop_stack",
        "ui_web_stack",
        "voice_activation_mode",
        "speaker_verification_enabled",
        "speaker_feature_backend",
        "speaker_verification_threshold",
        "speaker_auto_threshold_margin",
        "speaker_centroid_threshold",
        "speaker_centroid_margin",
        "speaker_negative_margin",
        "voice_challenge_enabled",
        "voice_challenge_mode",
        "voice_challenge_attempts",
        "voice_challenge_word_count",
        "voice_challenge_cache_seconds",
        "voice_challenge_words",
        "voice_challenge_protected_keywords",
        "attention_gate_enabled",
        "attention_mode",
        "attention_names",
        "wake_word_backend",
        "wake_word_model",
        "wake_word_threshold",
        "wake_energy_fallback",
        "wake_energy_threshold",
        "wake_energy_silence_ms",
        "wake_energy_max_seconds",
        "wake_trigger_pre_roll_ms",
        "wake_ack_beep",
        "startup_speech",
        "proactive_speech_enabled",
        "proactive_speech_in_fast_voice",
        "proactive_speech_poll_seconds",
        "proactive_speech_startup_delay_seconds",
        "proactive_speech_sources",
        "proactive_speech_max_per_hour",
        "proactive_speech_quiet_hours_start",
        "proactive_speech_quiet_hours_end",
        "proactive_speech_reminder_lookahead_minutes",
        "proactive_speech_calendar_lookahead_minutes",
        "proactive_speech_task_priority_threshold",
        "proactive_guardian_enabled",
        "proactive_guardian_in_fast_voice",
        "proactive_guardian_interval_seconds",
        "proactive_guardian_startup_delay_seconds",
        "guardian_battery_low_percent",
        "guardian_phone_battery_low_percent",
        "guardian_disk_low_percent",
        "guardian_stuck_task_minutes",
        "guardian_slow_response_count",
        "guardian_voice_mistake_threshold",
        "event_nervous_system_enabled",
        "event_nervous_system_interval_seconds",
        "event_nervous_system_notify_min_severity",
        "event_nervous_system_downloads_dir",
        "event_battery_low_percent",
        "event_agent_stuck_minutes",
        "barge_in_enabled",
        "barge_in_phrases",
        "barge_in_audio_monitor_enabled",
        "barge_in_interrupt_on_speech",
        "barge_in_capture_followup_commands",
        "barge_in_stt_model",
        "barge_in_min_energy_threshold",
        "barge_in_noise_multiplier",
        "barge_in_echo_grace_ms",
        "barge_in_min_active_ms",
        "barge_in_pre_roll_ms",
        "barge_in_silence_ms",
        "barge_in_max_seconds",
        "barge_in_min_audio_seconds",
        "barge_in_monitor_join_seconds",
        "barge_in_command_drain_timeout_seconds",
        "daily_companion_enabled",
        "daily_companion_poll_seconds",
        "daily_companion_morning_hour",
        "daily_companion_checkin_hours",
        "notification_dedupe_cooldown_minutes",
        "notification_voice_min_severity",
        "startup_ready_beep",
        "continuous_ready_beep",
        "stt_backend",
        "stt_model",
        "stt_device",
        "stt_compute_type",
        "stt_cpu_threads",
        "stt_vad_filter",
        "stt_vad_min_silence_ms",
        "stt_vad_speech_pad_ms",
        "stt_without_timestamps",
        "stt_max_new_tokens",
        "stt_repetition_penalty",
        "stt_no_repeat_ngram_size",
        "stt_hotwords",
        "stt_retry_on_blank",
        "stt_command_retries",
        "stt_min_command_chars",
        "stt_ignore_captures",
        "stt_silence_ms",
        "stt_pre_roll_ms",
        "desktop_vision_provider",
        "desktop_vision_model",
        "desktop_vision_allow_actions",
        "desktop_task_max_steps",
        "desktop_task_absolute_max_steps",
        "desktop_task_auto_extend_steps",
        "desktop_task_extend_by_steps",
        "desktop_task_no_progress_limit",
        "desktop_task_step_delay_seconds",
        "desktop_task_max_output_tokens",
        "desktop_task_recovery_enabled",
        "desktop_task_recovery_limit",
        "desktop_task_confirm_risky_actions",
        "browser_dom_enabled",
        "browser_dom_launch_chrome_debug",
        "browser_debug_port",
        "browser_dom_max_elements",
        "browser_playwright_enabled",
        "browser_playwright_headless",
        "browser_playwright_channel",
        "browser_playwright_timeout_seconds",
        "browser_playwright_max_steps",
        "app_accessibility_enabled",
        "app_accessibility_max_nodes",
        "visual_monitor_interval_seconds",
        "visual_monitor_realtime_fps",
        "visual_monitor_screen_capture_backend",
        "visual_monitor_change_threshold",
        "visual_monitor_analysis_enabled",
        "visual_monitor_analysis_interval_seconds",
        "visual_monitor_camera_index",
        "visual_monitor_context_events",
        "visual_monitor_planner_context_enabled",
        "office_docs_dir",
        "workspace_index_max_files",
        "workspace_index_snippet_chars",
        "workspace_index_extensions",
        "workspace_index_skip_dirs",
        "coding_projects_root",
        "intent_router_enabled",
        "intent_llm_enabled",
        "academic_projects_dir",
        "academic_project_max_sources",
        "academic_project_formats",
        "academic_project_llm_enabled",
        "academic_project_provider_chain",
        "git_integration_default_remote",
        "git_integration_default_branch",
        "git_integration_allow_commit",
        "git_integration_allow_push",
        "git_integration_timeout_seconds",
        "github_integration_prefer_gh_cli",
        "model_3d_output_dir",
        "model_3d_default_formats",
        "model_3d_default_segments",
        "model_3d_quality_default",
        "model_3d_blender_enabled",
        "model_3d_blender_path",
        "model_3d_studio_default_formats",
        "model_3d_studio_render_preview",
        "model_3d_studio_timeout_seconds",
        "model_3d_studio_fallback_procedural",
        "model_3d_studio_use_text_to_3d",
        "text_to_3d_enabled",
        "text_to_3d_provider_chain",
        "text_to_3d_timeout_seconds",
        "text_to_3d_poll_seconds",
        "text_to_3d_request_timeout_seconds",
        "text_to_3d_download_timeout_seconds",
        "text_to_3d_local_command",
        "text_to_3d_meshy_api_key_env",
        "text_to_3d_meshy_base_url",
        "text_to_3d_meshy_ai_model",
        "text_to_3d_meshy_model_type",
        "text_to_3d_meshy_refine_enabled",
        "text_to_3d_meshy_enable_pbr",
        "text_to_3d_meshy_should_remesh",
        "text_to_3d_meshy_target_polycount",
        "text_to_3d_meshy_auto_size",
        "text_to_3d_meshy_moderation",
        "text_to_3d_meshy_human_pose_mode",
        "text_to_3d_tripo_api_key_env",
        "text_to_3d_tripo_base_url",
        "text_to_3d_tripo_model_version",
        "text_to_3d_tripo_texture",
        "text_to_3d_tripo_pbr",
        "text_to_3d_tripo_texture_quality",
        "text_to_3d_tripo_geometry_quality",
        "text_to_3d_tripo_auto_size",
        "text_to_3d_tripo_export_uv",
        "text_to_3d_tripo_face_limit",
        "project_autopilot_docs_stale_seconds",
        "project_autopilot_doc_scan_max_files",
        "local_file_intelligence_roots",
        "local_file_intelligence_max_files",
        "local_file_intelligence_folder_max_files",
        "local_file_intelligence_max_file_bytes",
        "local_file_intelligence_text_chars",
    ]:
        assert key in config


def test_voice_defaults_require_friday_name_with_followups():
    config = json.loads((ROOT / "config.json").read_text(encoding="utf-8"))

    assert config["voice_activation_mode"] == "continuous"
    assert config["attention_gate_enabled"] is True
    assert config["attention_mode"] == "name"
    assert config["attention_action_recovery_enabled"] is False
    assert config["attention_safe_request_recovery_enabled"] is False
    assert config["conversation_followup_enabled"] is True
    assert int(config["conversation_followup_turns"]) >= 1


def test_coding_roots_resolve_under_configured_projects_root(monkeypatch, tmp_path):
    from core import config as core_config

    monkeypatch.setattr(
        core_config,
        "config_value",
        lambda key, default=None: str(tmp_path) if key == "coding_projects_root" else default,
    )

    assert core_config.resolve_coding_root() == tmp_path.resolve()
    assert core_config.resolve_coding_root(".") == tmp_path.resolve()
    assert core_config.resolve_coding_root(tmp_path.name) == tmp_path.resolve()
    assert core_config.resolve_coding_root("new-app") == (tmp_path / "new-app").resolve()


def test_default_coding_root_avoids_missing_container_desktop(monkeypatch, tmp_path):
    from core import config as core_config

    home = tmp_path / "root"
    repo = tmp_path / "workspace" / "second-brain"
    repo.mkdir(parents=True)
    monkeypatch.setattr(core_config, "ROOT_DIR", repo)
    monkeypatch.setattr(core_config.Path, "home", staticmethod(lambda: home))
    monkeypatch.setattr(
        core_config,
        "config_value",
        lambda key, default=None: "Desktop" if key == "coding_projects_root" else default,
    )

    assert core_config.default_coding_root() == (repo.parent / "friday-projects").resolve()


def test_voice_default_uses_free_neural_edge_voice():
    config = json.loads((ROOT / "config.json").read_text(encoding="utf-8"))

    assert config["voice_backend"] == "edge"
    assert config["fast_voice_use_local_tts"] is False
    assert str(config["edge_voice"]).endswith("Neural")


def test_requirements_are_pinned_and_complete():
    requirements = (ROOT / "requirements.txt").read_text(encoding="utf-8").splitlines()
    required = {
        "anthropic",
        "openwakeword",
        "openai-whisper",
        "faster-whisper",
        "sounddevice",
        "edge-tts",
        "elevenlabs",
        "pyttsx3",
        "pyautogui",
        "psutil",
        "duckduckgo-search",
        "yfinance",
        "alpha-vantage",
        "chromadb",
        "sentence-transformers",
        "scipy",
        "colorama",
        "plyer",
        "python-dotenv",
        "requests",
        "websocket-client",
        "playwright",
        "google-auth",
        "google-auth-oauthlib",
        "google-api-python-client",
        "pytest",
        "pytest-mock",
        "networkx",
        "tiktoken",
        "APScheduler",
        "pypdf",
        "beautifulsoup4",
        "youtube-transcript-api",
        "fastapi",
        "PyJWT",
        "uvicorn",
        "psycopg[binary]",
    }
    seen = {line.split("==")[0] for line in requirements if line and not line.startswith("#")}
    assert required <= seen
    assert all("==" in line for line in requirements if line and not line.startswith("#"))


def test_api_requirements_are_cloud_safe():
    requirements = (ROOT / "requirements-api.txt").read_text(encoding="utf-8").splitlines()
    required = {
        "anthropic",
        "fastapi",
        "PyJWT",
        "uvicorn",
        "psycopg[binary]",
        "python-dotenv",
        "requests",
        "websocket-client",
        "google-auth",
        "google-auth-oauthlib",
        "google-api-python-client",
    }
    local_only = {
        "openwakeword",
        "openai-whisper",
        "faster-whisper",
        "sounddevice",
        "edge-tts",
        "elevenlabs",
        "pyttsx3",
        "pyautogui",
        "chromadb",
        "sentence-transformers",
        "scipy",
        "plyer",
        "pytest",
        "pytest-mock",
    }
    seen = {line.split("==")[0] for line in requirements if line and not line.startswith("#")}
    assert required <= seen
    assert not (local_only & seen)
    assert all("==" in line for line in requirements if line and not line.startswith("#"))


def test_project_targets_python_314():
    assert (ROOT / ".python-version").read_text(encoding="utf-8").strip() == "3.14.5"
    assert 'requires-python = ">=3.14,<3.15"' in (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    assert sys.version_info >= (3, 14)
